### ISSUE TITLE
有mac 版本的吗

### ISSUE THREAD

**Issue by FutunnOpen** [FutunnOpen/OpenQuant#1]

**Comment by FutunnOpen** [comment]
暂时不支持， 后续看用户规模再考虑是否要提供mac版本

**Comment by FutunnOpen** [comment]
暂时不支持， 后续看用户规模再考虑是否要提供mac版本

**Comment by szmile2008** [comment]
可行的一个方案是在云服务器上开着 牛牛客户端， 把配置文件中的监听ip 改为0.0.0.0 , 这样mac系统也能调用python接口了

**Comment by jarrahwu** [comment]
我觉得最好就是 我们在python这边设置用户账号密码这些, 你们提供python 连接这样就比较友好了, 兼容性你都不需要管了, pycharm 这些 都是跨平台的

**Comment by emptist** [comment]
採用web接口多好嘛,這樣無論用什麼語言都很方便

**Comment by nerr** [comment]
赞成，需要友好的跨平台接口方式

**Comment by jarryji** [comment]
我也用mac, 但是用虚拟机跑FUTU,  mac版本的小问题还是蛮多的.
这个接口主要看功能性, 只有windows版本也没有问题.

**Comment by hellobiek** [comment]
嗯，目前只能这样了。关键是 机器泡一个vm非常消耗性能。

2017-04-11 16:46 GMT+08:00 jarryji <notifications@github.com>:
