### ISSUE TITLE
股票信息协议(Protocol:1014)股票类型应该修改

### ISSUE THREAD

**Issue by Cyanbull** [FutunnOpen/OpenQuant#11]
股票类型
0=所有    
1 = BOND--债券    
3 = STOCK--正股   
4 = ETF--ETF基金
5 = WARRANT--涡轮牛熊     
6 = IDX--指数 
本协议吧涡轮牛熊作为一个类型， 让用户无法区分涡轮和牛熊，建议次参数的涡轮牛熊分成两个类型

**Comment by FutunnOpen** [comment]
加个子类型 可以满足这个需求

**Comment by FutunnOpen** [comment]
3.32已经支持
