### ISSUE TITLE
大家好！请问我的连接一会就出现连接不上了，是什么问题呢 提示：由于目标计算机积极拒绝，无法连接。 127.0.0.1:11111

### ISSUE THREAD

**Issue by stormtrader** [FutunnOpen/OpenQuant#12]
大家好！请问我的连接一会就出现连接不上了，是什么问题呢
提示：由于目标计算机积极拒绝，无法连接。 127.0.0.1:11111

**Comment by FutunnOpen** [comment]
C++使用的事件模型只能并行处理64条连接。行情数据主动查询时尽量使用同一条连接、速度会更快一些。

**Comment by szmile2008** [comment]
除了连接上限限制,  2.0版本也修改了listen的逻辑， 规避出现连接不上的问题， 楼主确认下是否安装了群共享的3.29 新版本

**Comment by FutunnOpen** [comment]
请使用QQ群共享的最新3.32版 本
