### ISSUE TITLE
快速体验的方法

### ISSUE THREAD

**Issue by FutunnOpen** [FutunnOpen/OpenQuant#15]

**Comment by FutunnOpen** [comment]
不需要安装客户端。直接连接云端机器(ip=119.29.141.202 port=11111)。即可快速体验所有接口，无需API安装版本，也不需要打开客户端。

**Comment by Jintian** [comment]
只用来体验？ 还是可以一直这么玩，在server开客户端还是有点麻烦的

**Comment by FutunnOpen** [comment]
只是体验，如果自己开个客户端比较麻烦，可以自己申请一个云机器，费用一个月几十块钱。
