### ISSUE TITLE
这个需求你们看看,不重要不紧急

### ISSUE THREAD

**Issue by szargv** [FutunnOpen/OpenQuant#23]
主要用在牛熊证上
现在的持仓接口,能返回成本价
期望的持仓接口,能返回成本价,同时返回当时的标的物的价格.

比如腾讯的牛熊证,0.062买的,当时腾讯的价格是200,接口能够返回0.062和200
当然恒指的标的物是恒指当月期货,这个特殊

**Comment by FutunnOpen** [comment]
已记录
