### ISSUE TITLE
VS编译后的DLL，最新3.30客户端也无法创建11111端口

### ISSUE THREAD

**Issue by feige88903** [FutunnOpen/OpenQuant#25]
用VS2015编译，自动提升平台套件到v140， 编译无误。
安装最新客户端Ver.3.30.36301，把config.ini及这DLL放到plugin，11111端口永不存在。
是客户端的问题吗 ? 尝试联络 "FUTU 开放API群 108534288"，没回复。

**Comment by szmile2008** [comment]
目前api只能用群共享的3.29 版本 , 相关代码还没合入
