### ISSUE TITLE
请问发送请求后, server的回应时间

### ISSUE THREAD

**Issue by jboxsc163** [FutunnOpen/OpenQuant#32]
如果发送请求后, server 没有回应, 可能是网络问题, 或者任可原因
我应该等待多久, 判定求请求失败, 然后重新发送请求后

**Comment by FutunnOpen** [comment]
一般五秒没有回包，就可以判定为请求失败。

**Comment by FutunnOpen** [comment]
3.32对应的python脚本默认是10秒超时，
