### ISSUE TITLE
get_market_snapshot能否返回已经找到的资料?

### ISSUE THREAD

**Issue by szargv** [FutunnOpen/OpenQuant#40]
现在是获取两百支,只要有某一支不存在就返回错误了,能否返回其余的199支?

而且这个接口常超时

**Comment by FutunnOpen** [comment]
问题1：200支股票是同在一个协议包中发出的请求，一旦超时或错误，　所有数据都拿不到。
问题2：旧的python脚本是5超时， 现在已经改了10秒， 如果网络情况不太好， 建议这里还可以自行把python接口超时时间改长。
