### ISSUE TITLE
get_rt_ticker接口里的seq参数不起作用

### ISSUE THREAD

**Issue by moonspirit** [FutunnOpen/OpenQuant#44]
有时候pls和python链接断了，重连过程中会漏掉一些ticker，但是我希望我本地保存的ticker是完整的，我可以指定传我上次收到的最大seq来拉到这些数据么，现在seq参数好像不起作用，都当作-1处理

**Comment by FutunnOpen** [comment]
历史ticker 后续会单独 提供 接口
