### ISSUE TITLE
如何加入FUTU API 群 

### ISSUE THREAD

**Issue by hungchai** [FutunnOpen/OpenQuant#48]
提示要輸入python 或c++ code
要等多久才批准?

**Comment by leelilyfutunn** [comment]
写一行代码提交以后，应该很快就可以通过的啊

**Comment by hungchai** [comment]
昨天我寫了很多句

**Comment by hungchai** [comment]
我QQ 的 3043768260

**Comment by hungchai** [comment]
> 写一行代码提交以后，应该很快就可以通过的啊
過了這麼多天, 還沒有通过

**Comment by FutunnOpen** [comment]
FUTU 开放API群 108534288

**Comment by hungchai** [comment]
我那個ＱＱ　號是國際號，就算你們通過了，我也進不了，後來我再申請一個ＱＱ中國號就可以了
