### ISSUE TITLE
VS 2017 打不開pluginserver 的project

### ISSUE THREAD

**Issue by hungchai** [FutunnOpen/OpenQuant#55]
![virtualbox_win7pro64job2016_04_06_2017_21_59_35](https://cloud.githubusercontent.com/assets/10190523/26762223/32b7b076-4971-11e7-9445-23a66ba5bc2f.png)
報錯 "the operation cannot be completed

**Comment by FutunnOpen** [comment]
文件 中打开 PluginServer.vcxproj
