### ISSUE TITLE
手机端登录时电脑客户端level 2退出

### ISSUE THREAD

**Issue by luwening** [FutunnOpen/OpenQuant#7]
RT，手机端登录时电脑客户端level 2退出

牛牛号XXXX

**Comment by FutunnOpen** [comment]
这个是牛牛的互踢逻辑。如果在使用API时，请不要用该牛牛号在手机端登录。

**Comment by hlc926** [comment]
能否增加一个接口：恢复（使用）level2行情（美股是level1行情）

**Comment by FutunnOpen** [comment]
3.32 api版 本会自动 抢回level2 权限
